#!/bin/sh
#
#  ------------------------------------------------------------------------------------------------
#  Copyright (c) Microsoft Corporation
#  All rights reserved.
#
#  MIT License:
#
#  Permission is hereby granted, free of charge, to any person obtaining
#  a copy of this software and associated documentation files (the
#  "Software"), to deal in the Software without restriction, including
#  without limitation the rights to use, copy, modify, merge, publish,
#  distribute, sublicense, and/or sell copies of the Software, and to
#  permit persons to whom the Software is furnished to do so, subject to
#  the following conditions:
#
#  The above copyright notice and this permission notice shall be
#  included in all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
#  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
#  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
#  WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#  ------------------------------------------------------------------------------------------------
#
#  Script for launching git-tf.  Configures the classpath and starts Java
#  with the git-tf main class.
#

# Determine the platform
case `uname -s` in
	CYGWIN_NT*)
		PLATFORM=cygwin
		;;
	MINGW32_NT*)
		PLATFORM=mingw32
		;;
	*)
		PLATFORM=unix
		;;
esac

# On cygwin and mingw32, simply run the cmd script, otherwise we'd have to
# figure out how to mangle the paths appropriately for each platform
if [ "$PLATFORM" = "cygwin" ]; then
	COMSPEC_U=`cygpath -u "$COMSPEC"`
	GITTF_CMD=`cygpath -w "$0.cmd"`

	exec "$COMSPEC_U" /C "$GITTF_CMD" "$@"
elif [ "$PLATFORM" = "mingw32" ]; then
	exec "$COMSPEC" //C git-tf.cmd "$@"
fi

# BASE_DIRECTORY is the directory containing the Java libraries
if [ -z "$GITTF_HOME" ]; then
	BASE_DIRECTORY=`dirname "$0"`
else
	BASE_DIRECTORY="$GITTF_HOME"
fi

# Ensure that our main JAR exists
TEST_REQUIRED_JAR="$BASE_DIRECTORY/lib/com.microsoft.gittf.client.clc-*.jar"
if [ ! -f $TEST_REQUIRED_JAR ]; then
	echo "Unable to find a required JAR: $TEST_REQUIRED_JAR does not exist"
	exit
fi

# Add all libraries that shipped with the product to the classpath
GITTF_CLASSPATH=
export GITTF_CLASSPATH

for LIBRARY_JAR in "$BASE_DIRECTORY"/lib/*.jar ; do
	GITTF_CLASSPATH="$GITTF_CLASSPATH:$LIBRARY_JAR"
done

export TF_DISABLE_SYMBOLIC_LINK_PROP="true"

exec java -Xmx512m -classpath "$GITTF_CLASSPATH" \
	"-Dcom.microsoft.tfs.jni.native.base-directory=$BASE_DIRECTORY/native" \
	com.microsoft.gittf.client.clc.Main "$@"
